import { useState } from "react";
import LanguageSelector from "../components/dashboard/LanguageSelector.jsx";
import CodeEditor from "../components/dashboard/CodeEditor.jsx";
import AnalyzeButton from "../components/dashboard/AnalyzeButton.jsx";
import ResultPanel from "../components/dashboard/ResultPanel.jsx";
import analysisService from "../services/analysisService";

function Dashboard(){

    const [language, setLanguage] = useState("javascript");
    const [code, setCode] = useState("");
    const [analysis, setAnalysis] = useState("");
    const [loading, setLoading] = useState(false);
    
    const handleAnalyze = async()=>{
        if(!code.trim()){
            alert("Please enter some code first.");
            return;
        }
        setAnalysis("");
        setLoading(true);

        try{
            const result = await analysisService.analyze(language, code);
            setAnalysis(result.analysis);
        } catch(err){
            console.error(err);
            alert(err.response?.data?.message ||"Code analysis failed");
        } finally{
            setLoading(false);
        }
    };

    return(
        <div className="h-full p-6 flex flex-col bg-slate-950">

            <div className="mb-5 flex items-end justify-between">
                <div>

                    <h1 className="mt-1 text-2xl font-semibold tracking-tight text-white">
                        Analyze your code
                    </h1>

                    <p className="mt-1 text-sm text-slate-400">
                        Get intelligent insights, issues, and complexity analysis.
                    </p>
                </div>

                <AnalyzeButton onAnalyze={handleAnalyze} loading={loading}/>
            
            </div>

            <div className="flex min-h-0 flex-1 gap-5">

                <div className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-slate-800 bg-slate-900 shadow-sm">

                    <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3">
                        <div>
                            <p className="text-sm font-semibold text-slate-200">
                                Source Code
                            </p>

                            <p className="text-xs text-slate-500">
                                Write or paste your code
                            </p>
                        </div>

                        <LanguageSelector language={language} setLanguage={setLanguage}/>
                    
                    </div>

                    <div className="min-h-0 flex-1 p-2">
                        <CodeEditor code={code} setCode={setCode} language={language} />
                    </div>

                </div>

                <div className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-slate-800 bg-slate-900 shadow-sm">

                    <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3">
                        <div>
                            <p className="text-sm font-semibold text-slate-200">
                                AI Analysis
                            </p>

                            <p className="text-xs text-slate-500">
                                Insights generated by Gemini
                            </p>
                        </div>

                        <span className="rounded-full border border-slate-700 bg-slate-800 px-2 py-1 text-[10px] font-medium uppercase tracking-wider text-slate-400">
                            AI
                        </span>
                    </div>

                    <div className="min-h-0 flex-1">
                        <ResultPanel analysis={analysis}  loading={loading} />
                    </div>

                </div>

            </div>

        </div>
    );
}

export default Dashboard;